# Project name
name: flutterexercisethemovie
# Project description
description: Flutter Exercise The Movie
# Project version
version: 1.0.0+1
# Indicates that the package won't be published to any site
publish_to: none

# Specifies the minimum version of the Dart SDK to use in the project
environment:
  sdk: ">=2.18.0 <3.0.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter
  # Library for state management
  flutter_bloc: ^8.1.2
  # Library for internationalization
  flutter_localizations:
    sdk: flutter
  # Library for handling dates and times
  intl: ^0.17.0
  # Library for making HTTP requests
  http: ^0.13.5
  # Library for dependency injection
  get_it: ^7.2.0
  # Library for functional programming
  dartz: ^0.10.1
  # Library for object immutability
  freezed: ^2.3.2
  # Library for generating code for freezed
  freezed_annotation: ^2.2.0
  # Library for serializing and deserializing JSON objects
  json_serializable: ^6.6.1
  # Library for generating code for json_serializable
  json_annotation: ^4.8.0
  # Library for managing environment variables
  flutter_dotenv: ^5.0.2
  # Library for comparing objects in Dart
  equatable: ^2.0.5
  # Cupertino icons
  cupertino_icons: ^1.0.5
  # Library for page routing
  auto_route: ^6.3.0

# Development dependencies
dev_dependencies:
  # Library for unit testing with the BLoC pattern
  bloc_test: ^9.1.1
  # Library for testing in Flutter
  flutter_test:
    sdk: flutter
  # Library for creating mocks in tests
  mocktail: ^0.3.0
  # Library for generating code
  build_runner: ^2.3.3
  # Library for generating code for auto_route
  auto_route_generator:
  # Library for generating launcher icon.
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# Flutter-specific configuration
flutter:
  # Indicates that material design will be used
  uses-material-design: true
  # Code generation
  generate: true

  # List of resources that will be used in the project
  assets:
    - assets/
    - assets/images/splash.png
